class FrameDataConst:
    UNKNOWN = -1
    LEFT, RIGHT, UP, DOWN = 0, 1, 2, 3
    READY, JUMP, RACE, STOP, TURN, DOLPHIN_KICK = 0, 1, 2, 3, 4, 5
    BACKSTROKE, BUTTERFLY, FREESTYLE, BREASTSTROKE = 0, 1, 2, 3
    VERTICAL, HORIZONTAL = 0, 1
    
    MAP_DIRECTION = {-1: 'UNKNOWN', 0: 'LEFT', 1: 'RIGHT', 2: 'UP', 3: 'DOWN'}
    MAP_STATUS = {-1: 'UNKNOWN', 0: 'READY', 1: 'JUMP', 2: 'RACE', 3: 'STOP', 4: 'TURN', 5: 'DOLPHIN_KICK'}
    MAP_ORIENTATION = {-1: 'UNKNOWN', 0: 'VERTICAL', 1: 'HORIZONTAL'}
    MAP_STROKE = {-1: 'UNKNOWN', 0: 'BACKSTROKE', 1: 'BUTTERFLY', 2: 'FREESTYLE', 3: 'BREASTSTROKE'}